# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unJGKML-Vhls3Y3nb-9V5s75nxX1u_tJ
"""



!pip install transformers --quiet
!pip install datasets --quiet

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

def generate_email(recipient_name, event_name, special_instructions):
  prompt = f"Dear {recipient_name},\n\nI am writing to you regarding {event_name}.\n\n{special_instructions}\n\nSincerely,\n[Your Name]"
  generated_email = generator(prompt, max_length=200, num_return_sequences=1)
  return generated_email[0]['generated_text']

generator = pipeline("text-generation", model="gpt2")

recipient_name = "John Doe"
event_name = "Upcoming Webinar"
special_instructions = "Please RSVP by Friday."

email = generate_email(recipient_name, event_name, special_instructions)
print(email)

